version: '2'
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.254.0.0/16

services:
  app:
    container_name: teamspeak_app
    image: teamspeak:latest
    volumes:
      - ./teamspeak:/var/ts3server
      - ./whitelist.txt:/whitelist.txt
    ports:
      - 10011:10011
      - 30033:30033
      - 9987:9987/udp
    environment:
      - TS3SERVER_LICENSE=accept
      - TS3SERVER_IP_WHITELIST=/whitelist.txt
    restart: always
    networks:
      - network
  web:
    container_name: teamspeak_web
    image: ts3web:latest
    ports:
      - 8181:80
    restart: always
    networks:
      - network